### ISSUE TITLE
[form] Input file parameters

### ISSUE THREAD

**Issue by mlopezgva** [phpMv/phpMv-UI#11]
### [HtmlFormInput] addToProperty Input type file parameters
I am trying to set up an upload form like this:

```php
$importFrm = $this->sGui->htmlForm('import_frm', [
	$this->sGui->htmlHeader('', 3, $this->i18n->trans('mMenu.action.import')),
	$this->sGui->htmlDivider(''),
	$this->sGui->htmlInput('data_file', 'file'),
	$this->sGui->htmlButton('snd', $this->i18n->trans('btn.upload'))->asSubmit()
]);
$importFrm->getItem(2)
		  ->addToProperty('accept', 'application/csv;text/csv');
```

### Steps
See code above

### Expected Result
An input element with the `accept` attribute set.

### Actual Result
The attributes go to the `div` containing the `input` tag.

![image](https://user-images.githubusercontent.com/996070/58095108-84a0f380-7bd2-11e9-8fd5-e365968c2bbb.png)

Also, ` $importFrm->addPropertyValues('method', 'POST');` sets the `method` to the `div` _inside_ the `form` and not to the `form` tag.

***

**EDIT**: _OK, I solved the `method` by using `addToProperty()`, which is what should happen with the Input tag._

### Versions
Current; current Semantic/Fomantic; php 7.2.

**Comment by jcheron** [comment]
Logically, your form should be declared like that:
```php
		$importFrm = $this->sGui->htmlForm('import_frm', [
			new HtmlHeader('', 3, $this->i18n->trans('mMenu.action.import')),
			'<div class="ui divider"></div>',
			new HtmlInput('data_file', 'file'),
			(new HtmlButton('snd', $this->i18n->trans('btn.upload')))->asSubmit()
		]);
```
Do not instantiate internal objects using ``$this->sGui``, otherwise, the html/js compilation is done several times.

If you want to add a property on the input and not on its container (the div), you can use ``getDataField``:
```php
$importFrm->getItem(2)->getDataField()->setProperty('accept', 'application/csv;text/csv');
```

**Comment by mlopezgva** [comment]
> If you want to add a property on the input and not on its container (the div), you can use `getDataField`:

I have tried `$importFrm->getItem(2)->getDataField()->setProperty('accept', 'application/csv;text/csv');` and it still adds the attribute to the input's parent (an improvement, but it still leaves the input as is):

The code:
![imagen](https://user-images.githubusercontent.com/996070/58625726-55296f80-82d3-11e9-96fa-972e6fad061d.png)

Result:
![imagen](https://user-images.githubusercontent.com/996070/58625766-6ffbe400-82d3-11e9-8324-b32dcc3d4702.png)


> Do not instantiate internal objects using $this->sGui, otherwise, the html/js compilation is done several times.

I dislike having a dozen extra `use xxx\yyyy\zzz;`, but if it is really better that way...

**Comment by jcheron** [comment]
You should isolate the problem and try it:
```php
	$input = new HtmlInput('input', 'file');
	$input->getDataField()->setProperty('data-foo', 'bar')->setProperty('required', true);
	echo $input;
```
On my side, no problems:
![image](https://user-images.githubusercontent.com/2511052/58632510-f6b9bc80-82e5-11e9-8f22-f71adb9a6534.png)

This results in the form:

```php
	$input = new HtmlInput('input', 'file');
	$input->getDataField()->setProperty('data-foo', 'bar')->setProperty('required', true);
	$frm = $this->jquery->semantic()->htmlForm('frm', [
		new HtmlHeader('', 'Header'),
		new HtmlDivider(''),
		$input,
		new HtmlButton('', 'Okay')
	]);
	echo $frm;
```

**Comment by mlopezgva** [comment]
OK, using this approach:

![image](https://user-images.githubusercontent.com/996070/58636103-d0008380-82ef-11e9-8fb8-b7bcdc292236.png)

Worked as intended:

![image](https://user-images.githubusercontent.com/996070/58636133-e6a6da80-82ef-11e9-8d9d-28d92aa623b4.png)

I would've liked a less verbose approach, but not at least it's doing what it should. :-) Like you said, I should have tried to create the object outside the form constructor just to have better access (control) to it. It is maybe something wrong with the `getItem()->getDataField()` chain (it goes down one level, but it does not really returns any FormItem or Input object).

Thank you.

**Comment by mlopezgva** [comment]
Well, now I have some forms, time to do to the next level, so I'm trying this:

```php
// a whole Java-like-sized bunch of use after the namespace...
// DB
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Company;

// even more `use` for the SemanticGui...

class {
// ... some other unrelated code ...
	public function crudAction() {
// ... some other unrelated code ...
		$company = $this->getDoctrine()->getRepository(Company::class);
		$frm = $this->sGui->dataTable('comp', 'Company', $company);
		$frm->setFields(['company_name','company_type', 'country', 'obs', 'active','update']);
		$frm->setCaptions(['Company Name', 'Kind', 'Counrty', 'Comments', 'Active?', 'Action']);
		$frm->fieldsAs([
			'input'    => [['fluid' => true, 'rules'  => 'empty']],
			'dropdown' => [['CL'    => 'Client', 'EX' => 'Graphic Ex. Agency', 'CA' => 'Creative Agency'], true, ['fluid' => true]],
			'input'    => [['fluid' => true, 'rules'  => 'empty, length[2]']],
			'textarea' => [['fluid' => true]],
			'checkbox',
		]);
		$frm->asForm();
		$frm->fieldAsSubmit(5,"basic",null,"#lv4-2-submit",["ajax"=>["ajaxTransition"=>"random"]]);
	}
}
```

And I got this:

![image](https://user-images.githubusercontent.com/996070/58706095-5cbf4600-83b1-11e9-9ef2-44884e0a9d98.png)


Since I'm also new to Doctrine (ORMs aproach in general), I have no clue about anything here.
Please?

**Comment by jcheron** [comment]
You must specify the full name of the class:
```php
$frm = $this->sGui->dataTable('comp', 'App\Entity\Company', $company);
```
or
```php
$frm = $this->sGui->dataTable('comp', Company::class, $company);
```
with the appropriate import (``use App\Entity\Company``)

**Comment by mlopezgva** [comment]
Right, but it seems there is no `find()` method, or it requires a value. In the docs it does not mention if this method must be created or what it does. But I suppose `$company` is the dataset (->findAll() should do...).

Thanks.
