### ISSUE TITLE
Dropdown input when selected text not displayed on dropdown

### ISSUE THREAD

**Issue by martinadi** [phpMv/phpMv-UI#4]
when i select an option on dropdown, text not displayed on dropdown. so dropdown show like not selected

**Comment by jcheron** [comment]
Can you post your code please

**Comment by jcheron** [comment]
You should use the **asSelect** method on dropDown to have its items selectable:
```php
$dd=$semantic->htmlDropdown("dd","Select gender",["Male","Female"]);
$dd->asSelect("gender");
echo $dd;
```

**Comment by martinadi** [comment]
on demo site ( [http://phpmv-ui.kobject.net/](http://phpmv-ui.kobject.net/) ) also not working.
you can try : 
click semantic > on the right menu click form > go to no 7. Dropdown, try select a genre.

**Comment by jcheron** [comment]
ok, it is HtmlFormDropdown, not HtmlDropdown

There is indeed a problem, The default value must be initialized at the instantiation

```php
use Ajax\semantic\html\collections\form\HtmlFormDropdown;
$form=$semantic->htmlForm("frm9");
$form->addField(new HtmlFormDropdown("genre",array("Male","Female"),"Genre",0));
echo $form;
```
The value parameter can be an empty string:
```php
new HtmlFormDropdown("genre",array("Male","Female"),"Genre","");
```

**Comment by martinadi** [comment]
its work, thank you

**Comment by jcheron** [comment]
@martinadi: Thank you for reporting
