### ISSUE TITLE
setup and confguration

### ISSUE THREAD

**Issue by maximsamoilov** [phpMv/phpMv-UI#5]
Hi, I try use library in my joomla component. The elements are generated correctly, but does not work with the interactivity using jquery.
I connected jquery, semantic.css, semantic.js.

Could you explain to me what am I doing wrong or where I can read more about it?
Thanks!

**Comment by jcheron** [comment]
Hi,
can you post the relevant phpmv code?

**Comment by maximsamoilov** [comment]
This code I launch in template view

```
$semantic = $this->jquery->semantic();

$bt = $semantic->htmlButton("bt2", "Follow");
$bt->onClick("$(this).toggleText('Following','Follow')");
echo $bt->compile($this->jquery);
```

This code one of examples.

Property jquery I initialize in base view class:

```
use Ajax\php\symfony\JsUtils;

class PLmsBaseView extends JViewLegacy
{
	protected $jquery;

	public $item;
	public $items;

	public function __construct($config = array())
	{
		parent::__construct($config);

		$options = array(
			'driver' => 'Jquery',
			'bootstrap' => true,
			'semantic' => true,
			'defer' => true
		);

		$this->jquery = new JsUtils($options);
	}
}
```

Maybe I'm doing wrong initialization?

**Comment by jcheron** [comment]
Try to do
```php
    	echo $bt;
    	echo $this->jquery->compile($this->view);
```
```echo $bt``` is sufficient, since the button is created on the **$semantic** object.
the compile method generates the javascript code.

Normally, this code is in a symfony controller, and the $view variable is accessible on $this.
In your case, if you are in a view, you may need to do:
```echo $this->jquery->compile ($this);```

by cons, there is no **toggleText** method in jQuery, but you may have added it...

About Initialization : 
do you use bootstrap and semantic at the same time?

**Comment by jcheron** [comment]
to define the toggleText function, I added to the initialization:
```php
$this->jquery = new JsUtils($options);
$jquery->exec("$.fn.toggleText = function(t1, t2){this.text((this.text()==t1)?t2:t1);};",true);
```

**Comment by maximsamoilov** [comment]
I want to use only semantic.
I changed initilization:

```
$options = array(
	'semantic' => true
);

$this->jquery = new JsUtils($options);
```
It seems the problem is that javascript doesn't generate. I added native alert, it doesn't work also. 

```
$bt = $semantic->htmlButton("bt2", "Follow");
$bt->onClick("alert('test');");
echo $bt->compile($this->jquery);
```

**Comment by jcheron** [comment]
As I said initially, 
can you try :
```php
    	echo $bt;
    	echo $this->jquery->compile($this);
```
The compile method generates the javascript code, It produces the code for all the generated components and must always be called at the end

**Comment by jcheron** [comment]
no new good news, I guess it's solved ...
