### ISSUE TITLE
Phalcon autoload does not work?

### ISSUE THREAD

**Issue by Isstum** [phpMv/phpMv-UI#7]
Hi there, 
i am looking for a way to use the semantic-ui with phalcon (Version: 3.3.2). I cant get it working following the docs.

Error i got: 
```
[Sat Mar 31 09:59:17 2018] PHP Fatal error:  Uncaught Error: Class 'Ajax\php\phalcon\JsUtils' not found in /home/workspace/hours/app/config/services.php:116
Stack trace:
#0 [internal function]: Closure->{closure}()
#1 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#2 [internal function]: Phalcon\Di->get('jquery', NULL)
#3 [internal function]: Phalcon\Di->getShared('jquery')
#4 /home/workspace/hours/app/controllers/IndexController.php(13): Phalcon\Di\Injectable->__get('jquery')
#5 [internal function]: IndexController->indexAction()
#6 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(IndexController), 'indexAction', Array)
#7 [internal function]: Phalcon\Dispatcher->dispatch()
#8 /home/workspace/hours/public/index.php(42): Phalcon\Mvc\Application->handle()
#9 /home/workspace/hours/.htrouter.php(30): require_once('/home/wor...')
#10 {main}
  thrown in /home/workspace/hours/app/config/services.php on line 116
```

I installed phpmv via composer:
`composer.phar require phpmv/php-mv-ui 2.3.x-dev`
composer.json was created, files are there:
![screenshot_20180331_100311](https://user-images.githubusercontent.com/27882499/38161210-24fbbce0-34ba-11e8-9665-23c1d9154f4b.jpg)

I have to add the documented code to the *service/loader.php* AND i have to change the path to be an absolute one.

```php
<?php

$loader = new \Phalcon\Loader();

/**
 * We're a registering a set of directories taken from the configuration file
 */
$loader->registerDirs(
    [
        $config->application->controllersDir,
        $config->application->modelsDir
    ]
)->register();

$loader->registerNamespaces(array(
		'Ajax' => '/home/workspace/hours/vendor/phpmv/php-mv-ui/Ajax/'
))->register();

```

Is there anything i did wrong?

**Comment by jcheron** [comment]
Hi,
`/home/workspace/hours/`  is a strange path for a web application...
Are you sure that the web server has the rights of access to the directory `/home/workspace/hours/vendor/phpmv/php-mv-ui/Ajax/` ?

I will already put your application in a more compliant folder like `/var/www/html` ...
but in any case not in the `home` folder.

I would simply try:
`
chmod -R 0755 /home/workspace/hours/vendor/
`

What is the content of `services.php`?

**Comment by Isstum** [comment]
Hi there, 

as i am working offline i

**Comment by Isstum** [comment]
Hi there, 

i am using a special user ("workspace") and his home for development. 
That will give me some more space to play around without messing around on my system. 

And the webserver runs under the same user. So access shout not be a problem (i checked that :D ).

**Comment by jcheron** [comment]
Can you try with:
``` php
$loader->registerNamespaces(array(
		'Ajax' => __DIR__ . '/../../vendor/phpmv/php-mv-ui/Ajax/'
))->register();
```
there is a problem with the vendor directory (access or location).
the vendor directory seems well located, there remains only the problem of access rights

Can you display the permissions and show me the result:
`ls -l /home/workspace/hours`

**Comment by Isstum** [comment]
Happy Easter! 	Happy April Fool's Day!

Yes, this code works too!

I dont believe its an rights-related problem. Everything runs under the same user. 
Nevertheless i checked every folder and related file. Everthing looks good.

So, maybe just an hickup somewhere in my config? Dont want to mess you up :D
If so, just close the issue and dont mind me ;)

**Comment by jcheron** [comment]
Happy Easter too!
I do not leave a user in trouble even on Easter day :-)
There is no other possibility than the rights or location problem for this error.

Have you changed the rights as I suggested?
`chmod -R 0755 /home/workspace/hours/vendor/`

**Comment by Isstum** [comment]
Yes, i tried that. Does not solve the problem.

I just recreated the whole project and installed phpmv again. Same problem :D 

I believe there must be something wrong on my end. I cant figure it out. But i know how to make it work. So... nothing here to fix for you? Close the issue?

Thank you for your help!

**Comment by jcheron** [comment]
No there is nothing else to do.
Except that you can use the **composer autoloader**, instead of the phalcon autoloader:
in **app/config/loader.php**:
```php
/*$loader->registerNamespaces(array(
		'Ajax' => __DIR__ . '/../../vendor/phpmv/php-mv-ui/Ajax/'
))->register();
*/
require_once( __DIR__ ."/../../vendor/autoload.php");
```
If it still does not work, you can be sure it's a rights issue
