### ISSUE TITLE
Another CSS Framework: Fomantic-UI

### ISSUE THREAD

**Issue by mlopezgva** [phpMv/phpMv-UI#9]
I have found this add-on is using Semantic UI. Is there any way for it to use [FomanticUI](https://fomantic-ui.com), which has more up-to-date components?

I.e., 

- [Calendar module](https://fomantic-ui.com/modules/calendar.html), which I need for our new project,
- [Toasts/Notifiers](https://fomantic-ui.com/modules/toast.html),
- placeholders (this also exists in Semantic) and
- [sliders](https://fomantic-ui.com/modules/slider.html).

**Comment by jcheron** [comment]
Fomantic was created to continue active development of Semantic-UI.
Semantic-UI components running on phpMv-UI should also work in their Fomantic-UI version.

For the new components you mention (Toaster, Slider), they are still in Beta version in Fomantic-UI.
So I'm waiting for a little more stability to switch phpMv-UI from semantic to Fomantic.

In the meantime, you can use phpMv-UI with Fomantic or Semantic, and make by hand (in HTML) the few missing components.

**Comment by mlopezgva** [comment]
OK, the Calendar module seems to be out of beta, which is good news to me.
Yes, the toast could be rendered using the traditional way.
OTOH, moving to FomanticUI (or creating a new layer, like Bootstrap) right now is trivial, as it is still almost Semantic, except for the new elements and some coloring.

But I understand that creating support for it but not allowing the use of the new elements like toast or calendar it's kind of pointless.

[sigh] I'll wait. :-)

**Comment by mlopezgva** [comment]
Just one thing: which be the "correct" way to override the Semantic with FomanticUI injection? I mean, without tampering with the source. Thanks.

**Comment by jcheron** [comment]
There is nothing else to do but change the inclusions of css and js files, replacing Semantic with Fomantic.
You can use the new CDN: https://cdnjs.com/libraries/fomantic-ui

For the Calendar, personally, I prefer to use the default datePicker HTML5 component,
I find that the Fomantic component doesn't bring much benefit.

**Comment by mlopezgva** [comment]
Right, I modified the links. Thank you again.
